### ISSUE TITLE
java.lang.ExceptionInInitializerError on Android OS 4.0

### ISSUE THREAD

**Issue by LupoBianco** [msgpack/msgpack-java#189]
Hi. When I try to use msgpack 0.7x on android application i get this error caused by java.lang.NoSuchMethodException in MessageBuffer.java
Reading the code I see "sun.misc.unsafe" library is missing and I think it's the cause of NoSuchMethodException.
How do I resolve this issue?

full stacktrace:
```
01-30 13:27:18.282  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ Late-enabling CheckJNI
01-30 13:27:18.503  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.allocateMemory, referenced from method org.msgpack.core.buffer.MessageBuffer.newOffHeapBuffer
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10248: Lsun/misc/Unsafe;.allocateMemory (J)J
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0003
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.freeMemory, referenced from method org.msgpack.core.buffer.MessageBuffer.releaseBuffer
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10252: Lsun/misc/Unsafe;.freeMemory (J)V
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x001b
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.copyMemory, referenced from method org.msgpack.core.buffer.MessageBuffer.copyTo
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10251: Lsun/misc/Unsafe;.copyMemory (Ljava/lang/Object;JLjava/lang/Object;JJ)V
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x74 at 0x0010
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.getBoolean, referenced from method org.msgpack.core.buffer.MessageBuffer.getBoolean
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10253: Lsun/misc/Unsafe;.getBoolean (Ljava/lang/Object;J)Z
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0008
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.getByte, referenced from method org.msgpack.core.buffer.MessageBuffer.getByte
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10254: Lsun/misc/Unsafe;.getByte (Ljava/lang/Object;J)B
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0008
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.copyMemory, referenced from method org.msgpack.core.buffer.MessageBuffer.getBytes
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10251: Lsun/misc/Unsafe;.copyMemory (Ljava/lang/Object;JLjava/lang/Object;JJ)V
01-30 13:27:18.513  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x74 at 0x000f
01-30 13:27:18.523  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.getShort, referenced from method org.msgpack.core.buffer.MessageBuffer.getShort
01-30 13:27:18.523  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10259: Lsun/misc/Unsafe;.getShort (Ljava/lang/Object;J)S
01-30 13:27:18.523  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0008
01-30 13:27:18.533  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.putBoolean, referenced from method org.msgpack.core.buffer.MessageBuffer.putBoolean
01-30 13:27:18.533  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10260: Lsun/misc/Unsafe;.putBoolean (Ljava/lang/Object;JZ)V
01-30 13:27:18.533  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0008
01-30 13:27:18.533  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.putByte, referenced from method org.msgpack.core.buffer.MessageBuffer.putByte
01-30 13:27:18.533  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10261: Lsun/misc/Unsafe;.putByte (Ljava/lang/Object;JB)V
01-30 13:27:18.533  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0008
01-30 13:27:18.543  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.copyMemory, referenced from method org.msgpack.core.buffer.MessageBuffer.putByteBuffer
01-30 13:27:18.543  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10251: Lsun/misc/Unsafe;.copyMemory (Ljava/lang/Object;JLjava/lang/Object;JJ)V
01-30 13:27:18.543  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x74 at 0x002b
01-30 13:27:18.543  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.copyMemory, referenced from method org.msgpack.core.buffer.MessageBuffer.putByteBuffer
01-30 13:27:18.543  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10251: Lsun/misc/Unsafe;.copyMemory (Ljava/lang/Object;JLjava/lang/Object;JJ)V
01-30 13:27:18.543  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x74 at 0x0052
01-30 13:27:18.543  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.putByte, referenced from method org.msgpack.core.buffer.MessageBuffer.putByteBuffer
01-30 13:27:18.543  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10261: Lsun/misc/Unsafe;.putByte (Ljava/lang/Object;JB)V
01-30 13:27:18.543  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0073
01-30 13:27:18.543  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.copyMemory, referenced from method org.msgpack.core.buffer.MessageBuffer.putBytes
01-30 13:27:18.543  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10251: Lsun/misc/Unsafe;.copyMemory (Ljava/lang/Object;JLjava/lang/Object;JJ)V
01-30 13:27:18.543  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x74 at 0x000e
01-30 13:27:18.553  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.putShort, referenced from method org.msgpack.core.buffer.MessageBuffer.putShort
01-30 13:27:18.553  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10265: Lsun/misc/Unsafe;.putShort (Ljava/lang/Object;JS)V
01-30 13:27:18.553  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x000c
01-30 13:27:18.553  15251-15251/com.greenapes.sticazzi I/dalvikvm﹕ Could not find method sun.misc.Unsafe.copyMemory, referenced from method org.msgpack.core.buffer.MessageBuffer.toByteArray
01-30 13:27:18.553  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ VFY: unable to resolve virtual method 10251: Lsun/misc/Unsafe;.copyMemory (Ljava/lang/Object;JLjava/lang/Object;JJ)V
01-30 13:27:18.553  15251-15251/com.greenapes.sticazzi D/dalvikvm﹕ VFY: replacing opcode 0x74 at 0x0014
01-30 13:27:18.553  15251-15251/com.greenapes.sticazzi W/System.err﹕ java.lang.NoSuchMethodException: <init> [long, int]
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at java.lang.Class.getConstructorOrMethod(Class.java:460)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at java.lang.Class.getDeclaredConstructor(Class.java:588)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at org.msgpack.core.buffer.MessageBuffer.<clinit>(MessageBuffer.java:93)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at org.msgpack.core.buffer.OutputStreamBufferOutput.next(OutputStreamBufferOutput.java:35)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at org.msgpack.core.MessagePacker.prepareBuffer(MessagePacker.java:111)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at org.msgpack.core.MessagePacker.packString(MessagePacker.java:352)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at com.greenapes.sticazzi.MainActivity.basicUsage(MainActivity.java:46)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at com.greenapes.sticazzi.MainActivity.onCreate(MainActivity.java:28)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at android.app.Activity.performCreate(Activity.java:4531)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1071)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2150)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2229)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at android.app.ActivityThread.access$600(ActivityThread.java:139)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:99)
01-30 13:27:18.573  15251-15251/com.greenapes.sticazzi W/System.err﹕ at android.os.Looper.loop(Looper.java:154)
01-30 13:27:18.583  15251-15251/com.greenapes.sticazzi W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:4945)
01-30 13:27:18.583  15251-15251/com.greenapes.sticazzi W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
01-30 13:27:18.583  15251-15251/com.greenapes.sticazzi W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:511)
01-30 13:27:18.583  15251-15251/com.greenapes.sticazzi W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
01-30 13:27:18.583  15251-15251/com.greenapes.sticazzi W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
01-30 13:27:18.583  15251-15251/com.greenapes.sticazzi W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
01-30 13:27:18.583  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ Exception Ljava/lang/RuntimeException; thrown while initializing Lorg/msgpack/core/buffer/MessageBuffer;
01-30 13:27:18.583  15251-15251/com.greenapes.sticazzi D/AndroidRuntime﹕ Shutting down VM
01-30 13:27:18.583  15251-15251/com.greenapes.sticazzi W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40ac2228)
01-30 13:27:18.583  15251-15251/com.greenapes.sticazzi E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.ExceptionInInitializerError
            at org.msgpack.core.buffer.OutputStreamBufferOutput.next(OutputStreamBufferOutput.java:35)
            at org.msgpack.core.MessagePacker.prepareBuffer(MessagePacker.java:111)
            at org.msgpack.core.MessagePacker.packString(MessagePacker.java:352)
            at com.greenapes.sticazzi.MainActivity.basicUsage(MainActivity.java:46)
            at com.greenapes.sticazzi.MainActivity.onCreate(MainActivity.java:28)
            at android.app.Activity.performCreate(Activity.java:4531)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1071)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2150)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2229)
            at android.app.ActivityThread.access$600(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:4945)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [long, int]
            at org.msgpack.core.buffer.MessageBuffer.<clinit>(MessageBuffer.java:150)
            at org.msgpack.core.buffer.OutputStreamBufferOutput.next(OutputStreamBufferOutput.java:35)
            at org.msgpack.core.MessagePacker.prepareBuffer(MessagePacker.java:111)
            at org.msgpack.core.MessagePacker.packString(MessagePacker.java:352)
            at com.greenapes.sticazzi.MainActivity.basicUsage(MainActivity.java:46)
            at com.greenapes.sticazzi.MainActivity.onCreate(MainActivity.java:28)
            at android.app.Activity.performCreate(Activity.java:4531)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1071)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2150)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2229)
            at android.app.ActivityThread.access$600(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:4945)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NoSuchMethodException: <init> [long, int]
            at java.lang.Class.getConstructorOrMethod(Class.java:460)
            at java.lang.Class.getDeclaredConstructor(Class.java:588)
            at org.msgpack.core.buffer.MessageBuffer.<clinit>(MessageBuffer.java:93)
            at org.msgpack.core.buffer.OutputStreamBufferOutput.next(OutputStreamBufferOutput.java:35)
            at org.msgpack.core.MessagePacker.prepareBuffer(MessagePacker.java:111)
            at org.msgpack.core.MessagePacker.packString(MessagePacker.java:352)
            at com.greenapes.sticazzi.MainActivity.basicUsage(MainActivity.java:46)
            at com.greenapes.sticazzi.MainActivity.onCreate(MainActivity.java:28)
            at android.app.Activity.performCreate(Activity.java:4531)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1071)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2150)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2229)
            at android.app.ActivityThread.access$600(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:4945)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by xerial** [comment]
Messages related to sun.misc.Unsafe are just warnings. 

The true cause of this error is it cannot find the constructor of java.nio.DirectByteBuffer: https://android.googlesource.com/platform/libcore/+/master/luni/src/main/java/java/nio/DirectByteBuffer.java

**Comment by xerial** [comment]
https://android.googlesource.com/platform/libcore/+/c375a9cfd6ca0f557a4343a14f6c4115a1f20207
If you can use Android 4.3 or later, this error will not happen. 

@komamitsu 
Do you think we need to support Android 4.0?

**Comment by komamitsu** [comment]
According to https://developer.android.com/about/dashboards/index.html, the total share less than Android 4.3 is about 55%. So we'd better support them, I think.

**Comment by komamitsu** [comment]
@xerial Can you review this PR? https://github.com/msgpack/msgpack-java/pull/190
It works on Android 4.0.4 but still fails on 2.3.3. The share of v2.3.3 is only 7.8%, so maybe we can decide not to support the version.

**Comment by LupoBianco** [comment]
Hooray! works like a charm on android 4.0

Here un example test: 

```java
package com.greenapes.msgpack;

import android.app.Activity;
import android.os.Bundle;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.msgpack.jackson.dataformat.MessagePackFactory;
import java.io.IOException;


public class MainActivity extends Activity{

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        try {
            ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());

            // Setting my POJO
            ExamplePojo Hoooray = new ExamplePojo();
            Hoooray.name = "Lupobianco";
            Hoooray.age = 32;

            // Serialization
            byte[] bytes = objectMapper.writeValueAsBytes(Hoooray);

            // Deserialization
            ExamplePojo value = objectMapper.readValue(bytes, ExamplePojo.class);

            System.out.println("name: " + value.getName() +", age: " + value.getAge());

        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    static class ExamplePojo{
        public String name;
        public int age;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public int getAge() {
            return age;
        }

        public void setAge(int age) {
            this.age = age;
        }
    }
}

```
