### ISSUE TITLE
Compilation error while serializing the object

### ISSUE THREAD

**Issue by Anand-J-Kadhi** [msgpack/msgpack-java#226]
Hello,

I am trying to serialize an object but i recieved the following exception :

```
May 04, 2015 6:24:37 PM org.msgpack.template.builder.BuildContext build
SEVERE: builder: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  com.sprint.byteoperation.ROConversationCreatedEvent _$$_t;
  if ($2 == null) {
    _$$_t = new com.sprint.byteoperation.ROConversationCreatedEvent();
  } else {
    _$$_t = (com.sprint.byteoperation.ROConversationCreatedEvent) $2;
  }
  $1.readArrayBegin();
  if ($1.trySkipNil()) {  } else {
    org.msgpack.template.builder.DefaultBuildContext.readPrivateField($1, _$$_t, com.sprint.byteoperation.ROConversationCreatedEvent.class, "messageData", templates[0]);
  }
  $1.readArrayEnd();
  return _$$_t;
}

Exception in thread "main" org.msgpack.MessageTypeException: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  com.sprint.byteoperation.ROConversationCreatedEvent _$$_t;
  if ($2 == null) {
    _$$_t = new com.sprint.byteoperation.ROConversationCreatedEvent();
  } else {
    _$$_t = (com.sprint.byteoperation.ROConversationCreatedEvent) $2;
  }
  $1.readArrayBegin();
  if ($1.trySkipNil()) {  } else {
    org.msgpack.template.builder.DefaultBuildContext.readPrivateField($1, _$$_t, com.sprint.byteoperation.ROConversationCreatedEvent.class, "messageData", templates[0]);
  }
  $1.readArrayEnd();
  return _$$_t;
}

	at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:575)
	at org.msgpack.template.TemplateRegistry.lookupAfterBuilding(TemplateRegistry.java:472)
	at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:251)
	at org.msgpack.MessagePack.write(MessagePack.java:195)
	at com.sprint.byteoperation.VsbSerializer.serialize(VsbSerializer.java:27)
	at org.axonframework.serializer.MessageSerializer.serialize(MessageSerializer.java:114)
	at com.sprint.byteoperation.Initializer.main(Initializer.java:57)
Caused by: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  com.sprint.byteoperation.ROConversationCreatedEvent _$$_t;
  if ($2 == null) {
    _$$_t = new com.sprint.byteoperation.ROConversationCreatedEvent();
  } else {
    _$$_t = (com.sprint.byteoperation.ROConversationCreatedEvent) $2;
  }
  $1.readArrayBegin();
  if ($1.trySkipNil()) {  } else {
    org.msgpack.template.builder.DefaultBuildContext.readPrivateField($1, _$$_t, com.sprint.byteoperation.ROConversationCreatedEvent.class, "messageData", templates[0]);
  }
  $1.readArrayEnd();
  return _$$_t;
}

	at org.msgpack.template.builder.BuildContext.build(BuildContext.java:73)
	at org.msgpack.template.builder.DefaultBuildContext.buildTemplate(DefaultBuildContext.java:56)
	at org.msgpack.template.builder.JavassistTemplateBuilder.buildTemplate(JavassistTemplateBuilder.java:118)
	at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(AbstractTemplateBuilder.java:61)
	at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:562)
	... 6 more
Caused by: javassist.CannotCompileException: [source error] no such constructor: com.sprint.byteoperation.ROConversationCreatedEvent
	at javassist.CtBehavior.setBody(CtBehavior.java:446)
	at javassist.CtBehavior.setBody(CtBehavior.java:412)
	at javassist.CtNewMethod.make(CtNewMethod.java:138)
	at org.msgpack.template.builder.BuildContext.buildReadMethod(BuildContext.java:144)
	at org.msgpack.template.builder.BuildContext.build(BuildContext.java:65)
	... 10 more
Caused by: compile error: no such constructor: com.sprint.byteoperation.ROConversationCreatedEvent
	at javassist.compiler.MemberCodeGen.atMethodCallCore2(MemberCodeGen.java:593)
	at javassist.compiler.MemberCodeGen.atMethodCallCore(MemberCodeGen.java:575)
	at javassist.compiler.MemberCodeGen.atNewExpr(MemberCodeGen.java:302)
	at javassist.compiler.ast.NewExpr.accept(NewExpr.java:73)
	at javassist.compiler.CodeGen.atAssignCore(CodeGen.java:860)
	at javassist.compiler.CodeGen.atVariableAssign(CodeGen.java:793)
	at javassist.compiler.CodeGen.atAssignExpr(CodeGen.java:747)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:332)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:391)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:355)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
	at javassist.compiler.Javac.compileBody(Javac.java:223)
	at javassist.CtBehavior.setBody(CtBehavior.java:438)
	... 14 more
```
and the class is like : 

```
import org.axonframework.serializer.SerializedObject;
import org.axonframework.serializer.SerializedType;
import org.msgpack.annotation.Message;

@Message
public final class CreatedEvent {
	
	final private String conversationId;
	
	private String messageData;
	
	public CreatedEvent(String conversationId, String messageData){
		this.conversationId = conversationId;	
		this.messageData = messageData;
	}

	/**
	 * @return the messageData
	 */
	public String getMessageData() {
		return messageData;
	}

	/**
	 * @param messageData the messageData to set
	 */
	public void setMessageData(String messageData) {
		this.messageData = messageData;
	}

	/**
	 * @return the conversationId
	 */
	public String getConversationId() {
		return conversationId;
	}
}
```

and when i use the default constructor it works fine, but the problem is there is a final field for which i can't change the final modifier(therefore i cant use the default constructor), is there any solution over this ?

**Comment by komamitsu** [comment]
In msgpack-java v0.6.x, MessagePack can't serialize/deserialize an object that its class doesn't have default constructor unfortunately.

BTW, we added https://github.com/msgpack/msgpack-java/tree/v07-develop/msgpack-jackson in msgpack-java v0.7. With the library, you can handle the above issue easily like this.

```
    public final class CreatedEvent {
        final private String conversationId;
        private String messageData;

        @JsonCreator
        public CreatedEvent(
                @JsonProperty("conversationId") String conversationId,
                @JsonProperty("messageData") String messageData) {
            this.conversationId = conversationId;
            this.messageData = messageData;
        }
        :
    }

    {
        ObjectMapper mapper = new ObjectMapper(new MessagePackFactory());
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        mapper.writeValue(out, new CreatedEvent("conv", "msg"));
        mapper.readValue(new ByteArrayInputStream(out.toByteArray()), CreatedEvent.class);
    }
```

**Comment by Anand-J-Kadhi** [comment]
Making changes would be a lot bigger in this stage for me. Anyways, i will try with msgpack-java v0.7.
Thanks a lot for your help and the product.

**Comment by Anand-J-Kadhi** [comment]
I see that the @Message annotation and AbstractTemplate Class has been removed when i migrated from 0.6.9 to 0.7.0.p5 version. Is that intentional or i have to add another dependency for above classes.

**Comment by Anand-J-Kadhi** [comment]
How to handle Meta-data with the MsgPack serializer ?

**Comment by komamitsu** [comment]
The API of 0.7.x isn't compatible with the one of 0.6.x. I hope https://github.com/msgpack/msgpack-java/blob/v07-develop/msgpack-core/src/main/java/org/msgpack/core/example/MessagePackExample.java is useful to understand how to use the API of 0.7.x.

For `jackson-dataformat-msgpack`, you can use Jackson annotations (https://github.com/FasterXML/jackson-annotations).

**Comment by Anand-J-Kadhi** [comment]
Thanks, i understood. Only one question ,I am using axon by default it uses XStreamSerializer which handles metadata for which it has a metadata converter like this :

```

    /**
     * Class that marshals MetaData in the least verbose way.
     */
    private static final class MetaDataConverter extends MapConverter {

        public MetaDataConverter(Mapper mapper) {
            super(mapper);
        }

        @Override
        public boolean canConvert(Class type) {
            return MetaData.class.equals(type);
        }

        @Override
        public void marshal(Object source, HierarchicalStreamWriter writer, MarshallingContext context) {
            MetaData metaData = (MetaData) source;
            if (!metaData.isEmpty()) {
                super.marshal(new HashMap<String, Object>(metaData), writer, context);
            }
        }

        @Override
        public Object unmarshal(HierarchicalStreamReader reader, UnmarshallingContext context) {
            if (!reader.hasMoreChildren()) {
                return MetaData.emptyInstance();
            }
            Map<String, Object> contents = new HashMap<String, Object>();
            populateMap(reader, context, contents);
            if (contents.isEmpty()) {
                return MetaData.emptyInstance();
            } else {
                return MetaData.from(contents);
            }
        }
    }
```
Do msgpack has similar functionality for processing meta-data. If not can you suggest how to handle meta-data using msgpack.

**Comment by komamitsu** [comment]
@Anand-J-Kadhi Can you show me an usage example of `XStreamSerializer`?

**Comment by komamitsu** [comment]
@Anand-J-Kadhi Can I close this issue?
