### ISSUE TITLE
Jackson can't serialize Integer (or basic types)

### ISSUE THREAD

**Issue by fdinoff** [msgpack/msgpack-java#230]
The following fails with an IllegalStateException

```java
ObjectMapper msgPackObjectMapper = new ObjectMapper(new MessagePackFactory());
byte[] msgPack = msgPackObjectMapper.writeValueAsBytes(1); // Throws
```

```java
com.fasterxml.jackson.databind.JsonMappingException: The stack is empty
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:139)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:2881)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:2362)
        ...
Caused by: java.lang.IllegalStateException: The stack is empty
	at org.msgpack.jackson.dataformat.MessagePackGenerator.getStackTop(MessagePackGenerator.java:371)
	at org.msgpack.jackson.dataformat.MessagePackGenerator.addValueToStackTop(MessagePackGenerator.java:397)
	at org.msgpack.jackson.dataformat.MessagePackGenerator.writeNumber(MessagePackGenerator.java:284)
	at com.fasterxml.jackson.databind.ser.std.NumberSerializers$IntegerSerializer.serialize(NumberSerializers.java:138)
	at com.fasterxml.jackson.databind.ser.std.NumberSerializers$IntegerSerializer.serialize(NumberSerializers.java:131)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
       ...
```

I would expect the array returned to contain 0x01, which is what `out` would contain if done manually.

```java
ByteArrayOutputStream out = new ByteArrayOutputStream();
MessagePack.newDefaultPacker(out).packInt(1).close();
```

This appears to also fail for the other basic types such as booleans, BigInteger, and Strings.

**Comment by komamitsu** [comment]
@fdinoff Thanks for reporting this. I fixed it in https://github.com/msgpack/msgpack-java/pull/243.

You can write like this:
```
        ObjectMapper mapper = new ObjectMapper(new MessagePackFactory());
        mapper.disable(JsonParser.Feature.AUTO_CLOSE_SOURCE);
        mapper.disable(JsonGenerator.Feature.AUTO_CLOSE_TARGET);
        PipedOutputStream out = new PipedOutputStream();
        PipedInputStream in = new PipedInputStream(out);
        mapper.writeValue(out, 3.14);
        mapper.writeValue(out, "hello world");
        mapper.writeValue(out, 42);
        out.close();
        System.out.println(mapper.readValue(in, new TypeReference<Float>() {}));
        System.out.println(mapper.readValue(in, new TypeReference<String>() {}));
        System.out.println(mapper.readValue(in, new TypeReference<Integer>() {}));
        in.close();
```
