### ISSUE TITLE
unpack fail from a map

### ISSUE THREAD

**Issue by junstor** [msgpack/msgpack-java#248]
```java
        ByteArrayOutputStream stream = new ByteArrayOutputStream();
        MessagePacker packer = MessagePack.newDefaultPacker(stream);
        packer.packMapHeader(2);
        packer.packString("key1");
        packer.packString("value1");
        packer.packString("key2");
        packer.packString("value2");
        
        MessageUnpacker unpacker = MessagePack.newDefaultUnpacker(stream.toByteArray());
        int size = unpacker.unpackMapHeader();
        System.out.println(size);
        System.out.println(unpacker.unpackString());
        System.out.println(unpacker.unpackString());
        System.out.println(unpacker.unpackString());
        System.out.println(unpacker.unpackString());
```

In my case, I want to pack a map like: {"key1":"value1", "key2":"value2"} in msgpack. And then I unpacked it, I found that I can only get 3 fields (key1, value1, key2).

The result of the above code is : 
```java
2
key1
value1
key2
Exception in thread "main" java.io.EOFException
	at org.msgpack.core.MessageUnpacker.unpackString(MessageUnpacker.java:971)
	at com.funplus.fpnn.fpnn_java_api.App.main(App.java:60)
```

Please give me a hand, tks.

**Comment by junstor** [comment]
Sorry, I found the reason, I missed a packer.flush();   
Closed.
