### ISSUE TITLE
ExceptionInInitializerError because it did not find MessageBufferU

### ISSUE THREAD

**Issue by MereutaRadu** [msgpack/msgpack-java#273]
Hi,

I'm trying to upgrade from msgpack 0.5.3 to 0.7.0-M6. 

Followed the example from: https://github.com/msgpack/msgpack-java/blob/v07-develop/msgpack-core/src/test/java/org/msgpack/core/example/MessagePackExample.java, but my app always crashes with this error: 

`08-22 19:47:37.532    9501-9501/com.myapp.dev E/AndroidRuntime? FATAL EXCEPTION: main
    java.lang.ExceptionInInitializerError
            at org.msgpack.core.buffer.OutputStreamBufferOutput.next(OutputStreamBufferOutput.java:35)
            at org.msgpack.core.MessagePacker.ensureCapacity(MessagePacker.java:153)
            at org.msgpack.core.MessagePacker.writeByte(MessagePacker.java:158)
            at org.msgpack.core.MessagePacker.packArrayHeader(MessagePacker.java:448)
     Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.msgpack.core.buffer.MessageBufferU
            at org.msgpack.core.buffer.MessageBuffer.<clinit>(MessageBuffer.java:141)
            at org.msgpack.core.buffer.OutputStreamBufferOutput.next(OutputStreamBufferOutput.java:35)
            at org.msgpack.core.MessagePacker.ensureCapacity(MessagePacker.java:153)
            at org.msgpack.core.MessagePacker.writeByte(MessagePacker.java:158)
            at org.msgpack.core.MessagePacker.packArrayHeader(MessagePacker.java:448)
     Caused by: java.lang.ClassNotFoundException: org.msgpack.core.buffer.MessageBufferU
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:204)
            at java.lang.Class.forName(Class.java:169)
            at org.msgpack.core.buffer.MessageBuffer.<clinit>(MessageBuffer.java:127)
            at org.msgpack.core.buffer.OutputStreamBufferOutput.next(OutputStreamBufferOutput.java:35)
            at org.msgpack.core.MessagePacker.ensureCapacity(MessagePacker.java:153)
            at org.msgpack.core.MessagePacker.writeByte(MessagePacker.java:158)
            at org.msgpack.core.MessagePacker.packArrayHeader(MessagePacker.java:448)
     Caused by: java.lang.NoClassDefFoundError: org/msgpack/core/buffer/MessageBufferU
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:204)
            at java.lang.Class.forName(Class.java:169)
            at org.msgpack.core.buffer.MessageBuffer.<clinit>(MessageBuffer.java:127)
            at org.msgpack.core.buffer.OutputStreamBufferOutput.next(OutputStreamBufferOutput.java:35)
            at org.msgpack.core.MessagePacker.ensureCapacity(MessagePacker.java:153)
            at org.msgpack.core.MessagePacker.writeByte(MessagePacker.java:158)
            at org.msgpack.core.MessagePacker.packArrayHeader(MessagePacker.java:448)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.msgpack.core.buffer.MessageBufferU" on path: DexPathList[[zip file "/data/app/com.myapp.dev-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.myapp.dev-1, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:204)
            at java.lang.Class.forName(Class.java:169)
            at org.msgpack.core.buffer.MessageBuffer.<clinit>(MessageBuffer.java:127)
            at org.msgpack.core.buffer.OutputStreamBufferOutput.next(OutputStreamBufferOutput.java:35)
            at org.msgpack.core.MessagePacker.ensureCapacity(MessagePacker.java:153)
            at org.msgpack.core.MessagePacker.writeByte(MessagePacker.java:158)
            at org.msgpack.core.MessagePacker.packArrayHeader(MessagePacker.java:448)`

Do i have to add some extra stuff in the app's dependencies? 
It fails when i try to do any kind of packing.

Any suggestions on how to fix this ?
Thanks

**Comment by xerial** [comment]
Let me know the Android version number you are using.

**Comment by MereutaRadu** [comment]
Tested on a 4.4  and 4.3 device.

**Comment by xerial** [comment]
If you are using some compiler option that deletes unused class, this might be a cause. MessageBufferU is called by reflection and there is no direct import statement within the msgpack-core code.

**Comment by xerial** [comment]
If you are using ProGuard, MessageBufferU class might be deleted at bundling process. See also discussion at:
https://github.com/msgpack/msgpack-java/issues/101

This might be related:
http://stackoverflow.com/questions/7464035/how-to-tell-proguard-to-keep-everything

**Comment by xerial** [comment]
A quick workaround would be write an import statement in your code:
`import org.msgpack.core.buffer.MessageBufferU`
so that MessageBufferU will not be deleted.

**Comment by MereutaRadu** [comment]
Ok. Will check that in the morning. If it works i'll close the issue. Thanks a lot!

**Comment by MereutaRadu** [comment]
Proguard was my problem. Thanks for helping me :) Closing the issue.

**Comment by akanshSirohi** [comment]
@MereutaRadu I am facing the same error, can you tell me how you fixed this issue...??

**Comment by radu-mereuta** [comment]
@akanshSirohi Oh boy. That was such a long time ago :smile: 

The issue was that we were using Proguard to obfuscate the code and msgpack didn't like the fact that it's classes had their name changed (or they would outright not be bundled in the resulting apk). The fix was to just mark the particular class to be kept with the same name & to be bundled in the apk.

Something like `-keep class javax.** { *; }`

Can't give you the exact example as i'm no longer working on that project and i don't have access to the source code anymore
