### ISSUE TITLE
Fail to unpacke byte[] to JsonNode: Exception in thread "main" java.lang.NoSuchFieldError: STRICT_DUPLICATE_DETECTION

### ISSUE THREAD

**Issue by shirleyniara** [msgpack/msgpack-java#288]
Hi,

I am trying MessagePacker to pack JsonNode to byte array then unpack the byte array back to JsonNode. It gave me " java.lang.NoSuchFieldError: STRICT_DUPLICATE_DETECTION" exception during the unpack.

Here is my source code:
public class MessagePacker {

    public static void main(String[] args) throws IOException {
        ObjectMapper objMapper = new ObjectMapper(new MessagePackFactory() );

        String str = "{\"name\": \"test\", \"value\": \"12345\"}";
        JsonNode node = objMapper.readTree(str);
        byte[] packedBytes = objMapper.writeValueAsBytes(node);
        System.out.println(new String(packedBytes));
        JsonNode newNode = objMapper.readValue(packedBytes, JsonNode.class);
        System.out.println(newNode.toString());
    }
}

Here is the exception:
Exception in thread "main" java.lang.NoSuchFieldError: STRICT_DUPLICATE_DETECTION
	at org.msgpack.jackson.dataformat.MessagePackParser.<init>(MessagePackParser.java:116)
	at org.msgpack.jackson.dataformat.MessagePackParser.<init>(MessagePackParser.java:107)
	at org.msgpack.jackson.dataformat.MessagePackFactory._createParser(MessagePackFactory.java:90)
	at org.msgpack.jackson.dataformat.MessagePackFactory.createParser(MessagePackFactory.java:64)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2103)
	at com.niara.test.MessagePacker.main(MessagePacker.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

I checked the source code in MessagePackParser.java. MessagePackParser references Feature.STRICT_DUPLICATE_DETECTION which was added in jackson 2.6.0 release. In this case, please update the document that MessagePacker v7-M5 or newer requires jackson 2.6 or newer.

Thanks,

Shirley

**Comment by komamitsu** [comment]
It seems `JsonParser.Feature.STRICT_DUPLICATE_DETECTION` was added at 2.3.0.

https://github.com/FasterXML/jackson-core/commit/6fc0271dc60f513e31bd6649d53c9d665ab6f11d#diff-8ce9e55279cc32dc3ea176fa35d406b5R183

@shirleyniara How did you build your project? Which version of msgpack-java did you use?

**Comment by komamitsu** [comment]
Closing this issue. If you still have any problem, please reopen it?
