### ISSUE TITLE
MessageUnpacker.readPayloadAsReference throws MessageInsufficientBufferException for InputStream

### ISSUE THREAD

**Issue by xerial** [msgpack/msgpack-java#338]
In msgpack-core-0.8.1 MessgeUnpacker created by `MessagePack.newDefaultUnpacker(new GZIPInputStream(new ByteArrayInputStream(...))` throws MessageInsufficientBufferException.

```
org.msgpack.core.MessageInsufficientBufferException
[info] 	at org.msgpack.core.MessageUnpacker.getNextBuffer(MessageUnpacker.java:179)
[info] 	at org.msgpack.core.MessageUnpacker.nextBuffer(MessageUnpacker.java:189)
[info] 	at org.msgpack.core.MessageUnpacker.readPayload(MessageUnpacker.java:1241)
[info] 	at org.msgpack.core.MessageUnpacker.readPayloadAsReference(MessageUnpacker.java:1284)
```

```
    public void readPayload(ByteBuffer dst)
            throws IOException
    {
        while (true) {
            int dstRemaining = dst.remaining();
            int bufferRemaining = buffer.size() - position;
            if (bufferRemaining >= dstRemaining) {
                buffer.getBytes(position, dstRemaining, dst);
                position += dstRemaining;
                return;
            }
            buffer.getBytes(position, bufferRemaining, dst);
            position += bufferRemaining;

            nextBuffer(); <<---   this part throws the exception
        }
    }
```
For the same input data, 0.7.1 or using a byte array as an input source has no problem. 

I'll create a test case for reproducing this error.

**Comment by xerial** [comment]
I found this is related to the lifetime of MessageBuffer. Not a bug.
