### ISSUE TITLE
i got a very wierd problem.

### ISSUE THREAD

**Issue by easternHong** [msgpack/msgpack-java#365]
`Caused by: java.lang.IncompatibleClassChangeError: Couldn't find org.msgpack.annotation.Index.value
at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
at java.lang.reflect.Field.getAnnotation(Field.java:242)
at org.msgpack.template.builder.AbstractTemplateBuilder.getFieldIndex(Unknown Source)
at org.msgpack.template.builder.AbstractTemplateBuilder.toFieldEntries(Unknown Source)
at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(Unknown Source)
at org.msgpack.template.TemplateRegistry.buildAndRegister(Unknown Source)
at org.msgpack.template.TemplateRegistry.lookupAfterBuilding(Unknown Source)
at org.msgpack.template.TemplateRegistry.lookup(Unknown Source)
at org.msgpack.template.TemplateRegistry.lookupGenericTypeImpl0(Unknown Source)
at org.msgpack.template.TemplateRegistry.lookupGenericTypeImpl(Unknown Source)
at org.msgpack.template.TemplateRegistry.lookupGenericType(Unknown Source)
at org.msgpack.template.TemplateRegistry.lookup(Unknown Source)
at org.msgpack.template.builder.ReflectionTemplateBuilder.toTemplates(Unknown Source)
at org.msgpack.template.builder.ReflectionTemplateBuilder.buildTemplate(Unknown Source)
at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(Unknown Source)
at org.msgpack.template.TemplateRegistry.buildAndRegister(Unknown Source)
at org.msgpack.template.TemplateRegistry.lookupAfterBuilding(Unknown Source)
at org.msgpack.template.TemplateRegistry.lookup(Unknown Source)
at org.msgpack.MessagePack.read(Unknown Source)`

somebody please help me .
thanks

**Comment by komamitsu** [comment]
@easternHong Could you paste your code here that reproduces the error?

**Comment by easternHong** [comment]
sample like this
https://gist.github.com/easternHong/33d3f3153dea8e13f61998e7edb9d837

**Comment by easternHong** [comment]
but some time it will be ok.

**Comment by komamitsu** [comment]
Ah, libcore... Are you using MessagePack on Android? Which versions of the OS and msgpack-java?

**Comment by easternHong** [comment]
Android os 21+
msgpack 0.6.12

sorrry,i will update my local msgpack to 0.8.7 ,and keep feeding back .

**Comment by easternHong** [comment]
Android os: 21+
msgpack:0.6.12

i get the jar from the site:
http://repo1.maven.org/maven2/org/msgpack/msgpack/0.6.12/

**Comment by komamitsu** [comment]
@easternHong 
Oh, you executed the codes from JNI? > `and this is invoked from native layer`
I failed to reproduce this issue but I didn't try with calling from JNI...

**Comment by komamitsu** [comment]
I'm closing this issue for now. If you still have this issue, please reopen it.
