### ISSUE TITLE
What's wrong with this: msgpack cannot serialize generic class ?

### ISSUE THREAD

**Issue by fwensen** [msgpack/msgpack-java#399]
this is my interface:
`public interface Serializer {

```
<T> byte[] serialize(T obj);
<T> T deserialize(byte[] bytes, Class<T> clazz);
```

}`
and the msgpack impl: 
`public class MsgPackSerializer implements Serializer{

```
@Override
public <T> byte[] serialize(T obj) {

    MessagePack msgPack = new MessagePack();
    msgPack.register(obj.getClass());
    byte[] raw = null;  
    try {
        raw = msgPack.write(obj);
    } catch (IOException e) {
        e.printStackTrace();
    }  
    msgPack.unregister(obj.getClass());
    return raw;

}

@SuppressWarnings("unchecked")
@Override
public <T> T deserialize(byte[] bytes, Class<T> clazz) {

    MessagePack msgPack = new MessagePack();
    msgPack.register(clazz);
    try {
        return (T) msgPack.read(bytes, clazz);
    } catch (IOException e) {
        e.printStackTrace();
    } finally {
        msgPack.unregister(clazz);
    }
    return null;
}
```

}`
the Message:
`@Message
public class TestObj {

```
private final int a;
private final String b;
public TestObj(int a, String b) {
    this.a = a;
    this.b = b;
}

public int getA() {
    return this.a;
}

public String getB() {
    return this.b;
}
```

}`

but when i test it:
`public class TestMsgPackSerializer {

```
Serializer serilizer;
TestObj obj;

@Before
public void setUp() {
    serilizer = new MsgPackSerializer();
    obj = new TestObj(1,"hello");
}

@Test
public void testSerializer() {

    TestObj out;
    byte[] bytes = serilizer.serialize(obj);
    out = serilizer.deserialize(bytes, TestObj.class);
    assertEquals(obj.getA(), out.getA());
}
```

}`
and it give me the following message:
`十月 23, 2016 9:26:11 下午 org.msgpack.template.builder.BuildContext build
严重: builder: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  cn.uestc.indoorposition.communication.message.TestObj _$$_t;
  if ($2 == null) {
    _$$_t = new cn.uestc.indoorposition.communication.message.TestObj();
  } else {
    _$$_t = (cn.uestc.indoorposition.communication.message.TestObj) $2;
  }
  $1.readArrayBegin();
  $1.readArrayEnd();
  return _$$_t;
}`
the junit output: 
`org.msgpack.MessageTypeException: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  cn.uestc.indoorposition.communication.message.TestObj _$$_t;
  if ($2 == null) {
    _$$_t = new cn.uestc.indoorposition.communication.message.TestObj();
  } else {
    _$$_t = (cn.uestc.indoorposition.communication.message.TestObj) $2;
  }
  $1.readArrayBegin();
  $1.readArrayEnd();
  return _$$_t;
}

```
at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:575)
at org.msgpack.template.TemplateRegistry.register(TemplateRegistry.java:158)
at org.msgpack.MessagePack.register(MessagePack.java:602)
at cn.uestc.indoorposition.communication.message.MsgPackSerializer.serialize(MsgPackSerializer.java:17)
at cn.uestc.indoorposition.communication.message.TestMsgPackSerializer.testSerializer(TestMsgPackSerializer.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Caused by: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  cn.uestc.indoorposition.communication.message.TestObj _$$_t;
  if ($2 == null) {
    _$$_t = new cn.uestc.indoorposition.communication.message.TestObj();
  } else {
    _$$_t = (cn.uestc.indoorposition.communication.message.TestObj) $2;
  }
  $1.readArrayBegin();
  $1.readArrayEnd();
  return _$$_t;
}

```
at org.msgpack.template.builder.BuildContext.build(BuildContext.java:73)
at org.msgpack.template.builder.DefaultBuildContext.buildTemplate(DefaultBuildContext.java:56)
at org.msgpack.template.builder.JavassistTemplateBuilder.buildTemplate(JavassistTemplateBuilder.java:116)
at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(AbstractTemplateBuilder.java:61)
at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:562)
... 28 more
```

Caused by: javassist.CannotCompileException: [source error] no such constructor
    at javassist.CtBehavior.setBody(CtBehavior.java:417)
    at javassist.CtBehavior.setBody(CtBehavior.java:383)
    at javassist.CtNewMethod.make(CtNewMethod.java:138)
    at org.msgpack.template.builder.BuildContext.buildReadMethod(BuildContext.java:144)
    at org.msgpack.template.builder.BuildContext.build(BuildContext.java:65)
    ... 32 more
Caused by: compile error: no such constructor
    at javassist.compiler.MemberCodeGen.atMethodCallCore2(MemberCodeGen.java:593)
    at javassist.compiler.MemberCodeGen.atMethodCallCore(MemberCodeGen.java:575)
    at javassist.compiler.MemberCodeGen.atNewExpr(MemberCodeGen.java:302)
    at javassist.compiler.ast.NewExpr.accept(NewExpr.java:73)
    at javassist.compiler.CodeGen.atAssignCore(CodeGen.java:860)
    at javassist.compiler.CodeGen.atVariableAssign(CodeGen.java:793)
    at javassist.compiler.CodeGen.atAssignExpr(CodeGen.java:747)
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:332)
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
    at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:391)
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:355)
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
    at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
    at javassist.compiler.Javac.compileBody(Javac.java:223)
    at javassist.CtBehavior.setBody(CtBehavior.java:409)
    ... 36 more
`
Could someone can tell me what's wrong with my code?
thanks

**Comment by komamitsu** [comment]
@fwensen Sorry for my late reply. You need to remove `final` keyword from the instance variables of TestObj and make them public or add setter methods.

**Comment by fwensen** [comment]
thanks

2017-01-03 22:18 GMT+08:00 Mitsunori Komatsu <notifications@github.com>:

**Comment by komamitsu** [comment]
Closing this issue for now. If you still have this issue, please reopen it.

**Comment by arganzheng** [comment]
I write a Utils for this purpose:

```

import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayDeque;
import java.util.Collections;
import java.util.Deque;
import java.util.List;
import java.util.Map;

import org.msgpack.MessagePack;
import org.msgpack.template.Template;
import org.msgpack.template.Templates;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * @author zhengzhibin
 * @date 2018/12/09
 */
public abstract class MessagePackUtils {

    private static final Logger LOGGER = LoggerFactory.getLogger(MessagePackUtils.class);

    // singleton
    private static MessagePack msgpack = new MessagePack();

    /**
     * 序列化对象
     * 
     * @param obj
     * @return
     */
    public static <T> byte[] serializeObject(T obj) {
        register(obj.getClass());

        try {
            return msgpack.write(obj);
        } catch (IOException e) {
            throw new RuntimeException("MessagePack serializeObject error.", e);
        }
    }

    public static <T> T deserializeObject(byte[] bytes, Class<T> clazz) {
        try {
            return msgpack.read(bytes, clazz);
        } catch (IOException e) {
            throw new RuntimeException("MessagePack deserializeObject error.", e);
        }
    }

    public static <T> byte[] serializeList(List<T> obj, Class<T> clazz) {
        register(clazz);

        try {
            return msgpack.write(obj);
        } catch (IOException e) {
            throw new RuntimeException("MessagePack serializeList error.", e);
        }
    }

    public static <T> List<T> deserializeList(byte[] bytes, Class<T> clazz) {
        Template<T> elementTemplate = msgpack.lookup(clazz);
        Template<List<T>> listTmpl = Templates.tList(elementTemplate);

        try {
            return msgpack.read(bytes, listTmpl);
        } catch (IOException e) {
            throw new RuntimeException("MessagePack deserializeList error.", e);
        }
    }

    public static byte[] serializeMap(Map<?, ?> map, Class<?> keyClass, Class<?> valueClass) {
        if (map == null || map.isEmpty()) {
            return new byte[0];
        }

        register(keyClass);
        register(valueClass);

        try {
            return msgpack.write(map);
        } catch (IOException e) {
            throw new RuntimeException("MessagePack serializeMap error.", e);
        }
    }

    public static <K, V> Map<K, V> deserializeMap(byte[] bytes, Class<K> keyClass, Class<V> valueClass) {
        if (bytes == null || bytes.length == 0) {
            return Collections.emptyMap();
        }

        Template<K> keyTemplate = msgpack.lookup(keyClass);
        Template<V> valueTemplate = msgpack.lookup(valueClass);
        Template<Map<K, V>> mapTmpl = Templates.tMap(keyTemplate, valueTemplate);

        try {
            return msgpack.read(bytes, mapTmpl);
        } catch (IOException e) {
            throw new RuntimeException("MessagePack deserializeMap error.", e);
        }
    }

    private static void register(Class<?> clazz) {
        Template<?> tmpl = null;
        try {
            tmpl = msgpack.lookup(clazz);
        } catch (Exception e) {
            // do nothing
        }
        if (tmpl == null) {
            Deque<Class<?>> visited = new ArrayDeque<>();
            register(clazz, visited);
            for (Class<?> clz : visited) {
                registerClassForTemplate(clz);
            }
        }
    }

    /**
     * 其实就是一个后续遍历，先注册 属性，再注册自己。
     * 
     * @param clazz
     * @param visited
     */
    private static void register(Class<?> clazz, Deque<Class<?>> visited) {
        // 如果对象已被处理过，则返回，针对于 A、B对象相互组合的情况，否则会循环递归，导致StackOverFlow
        if (visited.contains(clazz)) {
            return;
        }

        if (BeanUtils.isSimpleProperty(clazz)) {
            return;
        }

        visited.push(clazz);

        do {
            Field[] fields = clazz.getDeclaredFields();

            for (Field field : fields) {
                field.setAccessible(true);

                if (Modifier.isStatic(field.getModifiers())) {
                    continue;
                }

                Class<?> t = field.getType();
                if (BeanUtils.isSimpleProperty(t)) {
                    continue;
                } else {
                    register(t, visited);
                }
            }
            // 获取该类型的父类Class实例，然后继续该循环
            clazz = clazz.getSuperclass();
        } while (clazz != null);
    }

    private static void registerClassForTemplate(Class<?> clazz) {
        Template<?> tmpl = null;
        try {
            tmpl = msgpack.lookup(clazz);
        } catch (Exception e) {
        }
        if (tmpl == null) {
            LOGGER.info("register Class {} For Template.", clazz);
            msgpack.register(clazz);
        } else {
            if (LOGGER.isDebugEnabled()) {
                LOGGER.debug("Class {} already register For Template.", clazz);
            }
        }
    }

}
```
