### ISSUE TITLE
org.msgpack.MessageTypeException: Expected raw value, but got boolean

### ISSUE THREAD

**Issue by PriyankaKamthe** [msgpack/msgpack-java#418]
I have successfully implemented msgPack in Android Application. But I am facing issue `Expected raw value, but got boolean` when I runs application in Device with API level below 22. If I run same application in Device  which having API level above 22 everything works fine. I am not able to find-out whats going wrong.
I am using Dependency `org.msgpack:msgpack:0.6.12` 
Following is my deserializing Android Code;

```
private T readMessagePack(byte[] response, Class<T> responseType) throws Exception
    {       
        MessagePack msgpack = new MessagePack();
        TemplateRegistry registry = new TemplateRegistry(null);
        ReflectionTemplateBuilder builder = new ReflectionTemplateBuilder(registry);
        Template<T> objTemplate = builder.buildTemplate(responseType);
        BufferUnpacker unpacker = msgpack.createBufferUnpacker();
        unpacker.resetReadByteCount();
        unpacker.wrap(response);
        return objTemplate.read(unpacker, null);

    }
```
Logcat Error:

```
Caused by: org.msgpack.MessageTypeException: Expected raw value, but got boolean
at org.msgpack.unpacker.Accept.acceptBoolean(Accept.java:33)
at org.msgpack.unpacker.MessagePackUnpacker.readOneWithoutStackLarge(MessagePackUnpacker.java:154)
at org.msgpack.unpacker.MessagePackUnpacker.readOneWithoutStack(MessagePackUnpacker.java:139)
at org.msgpack.unpacker.MessagePackUnpacker.readOne(MessagePackUnpacker.java:73)
at org.msgpack.unpacker.MessagePackUnpacker.readString(MessagePackUnpacker.java:472)
at org.msgpack.template.StringTemplate.read(StringTemplate.java:46)
at org.msgpack.template.StringTemplate.read(StringTemplate.java:25)
at org.msgpack.template.builder.ReflectionTemplateBuilder$FieldTemplateImpl.read(ReflectionTemplateBuilder.java:70)
at org.msgpack.template.builder.ReflectionTemplateBuilder$ReflectionClassTemplate.read(ReflectionTemplateBuilder.java:143)
```

**Comment by PriyankaKamthe** [comment]
This [answer](https://github.com/msgpack/msgpack-java/issues/98) solved my issue.

**Comment by komamitsu** [comment]
I'm closing this issue. If you still have any problem, please reopen it.
