### ISSUE TITLE
Compilation error while running load test of 100000 serialization

### ISSUE THREAD

**Issue by abhisheksahani192** [msgpack/msgpack-java#424]
after running for 52000 iteration i am getting compilation error while serializing POJO.

Jun 14, 2017 6:05:30 PM org.msgpack.template.builder.BuildContext build
SEVERE: builder: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  com.games24x7.snappytest.Message _$$_t;
  if ($2 == null) {
    _$$_t = new com.games24x7.snappytest.Message();
  } else {
    _$$_t = (com.games24x7.snappytest.Message) $2;
  }
  $1.readArrayBegin();
  if ($1.trySkipNil()) {  } else {
    org.msgpack.template.builder.DefaultBuildContext.readPrivateField($1, _$$_t, com.games24x7.snappytest.Message.class, "uniqueIdentifier", templates[0]);
  }
  $1.readArrayEnd();
  return _$$_t;
}

Exception in thread "main" org.msgpack.MessageTypeException: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  com.games24x7.snappytest.Message _$$_t;
  if ($2 == null) {
    _$$_t = new com.games24x7.snappytest.Message();
  } else {
    _$$_t = (com.games24x7.snappytest.Message) $2;
  }
  $1.readArrayBegin();
  if ($1.trySkipNil()) {  } else {
    org.msgpack.template.builder.DefaultBuildContext.readPrivateField($1, _$$_t, com.games24x7.snappytest.Message.class, "uniqueIdentifier", templates[0]);
  }
  $1.readArrayEnd();
  return _$$_t;
}

	at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:575)
	at org.msgpack.template.TemplateRegistry.lookupAfterBuilding(TemplateRegistry.java:472)
	at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:251)
	at org.msgpack.template.builder.ReflectionTemplateBuilder.toTemplates(ReflectionTemplateBuilder.java:199)
	at org.msgpack.template.builder.ReflectionTemplateBuilder.buildTemplate(ReflectionTemplateBuilder.java:181)
	at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(AbstractTemplateBuilder.java:61)
	at com.games24x7.snappytest.Gzip.compress(Gzip.java:109)
	at com.games24x7.snappytest.Gzip.messagepeackwithzlib(Gzip.java:192)
	at com.games24x7.snappytest.Gzip.main(Gzip.java:262)
Caused by: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  com.games24x7.snappytest.Message _$$_t;
  if ($2 == null) {
    _$$_t = new com.games24x7.snappytest.Message();
  } else {
    _$$_t = (com.games24x7.snappytest.Message) $2;
  }
  $1.readArrayBegin();
  if ($1.trySkipNil()) {  } else {
    org.msgpack.template.builder.DefaultBuildContext.readPrivateField($1, _$$_t, com.games24x7.snappytest.Message.class, "uniqueIdentifier", templates[0]);
  }
  $1.readArrayEnd();
  return _$$_t;
}

	at org.msgpack.template.builder.BuildContext.build(BuildContext.java:73)
	at org.msgpack.template.builder.DefaultBuildContext.buildTemplate(DefaultBuildContext.java:56)
	at org.msgpack.template.builder.JavassistTemplateBuilder.buildTemplate(JavassistTemplateBuilder.java:119)
	at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(AbstractTemplateBuilder.java:61)
	at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:562)
	... 8 more
Caused by: javassist.CannotCompileException: by java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "com/games24x7/snappytest/Message_$$_Template_801045052_0"
	at javassist.ClassPool.toClass(ClassPool.java:1099)
	at javassist.CtClass.toClass(CtClass.java:1265)
	at org.msgpack.template.builder.BuildContext.createClass(BuildContext.java:154)
	at org.msgpack.template.builder.BuildContext.build(BuildContext.java:68)
	... 12 more
Caused by: java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "com/games24x7/snappytest/Message_$$_Template_801045052_0"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.ClassPool.toClass2(ClassPool.java:1112)
	at javassist.ClassPool.toClass(ClassPool.java:1093)
	... 15 more

**Comment by abhisheksahani192** [comment]
my json has embedded json in that case above exception is coming , if i remove embedded json then there is no compilation error of duplicate class

**Comment by komamitsu** [comment]
@abhisheksahani192 Can you give an example that reproduces the error?

**Comment by komamitsu** [comment]
I'm closing this issue. If you still have a trouble on this issue, please re-open.
