### ISSUE TITLE
msgpack take 100% cpu usage

### ISSUE THREAD

**Issue by yinhaibo** [msgpack/msgpack-java#433]
I have used msgpack-java in my program. The cpu usage will up to 100%, and cannot go down. I check all my thread, and using jstack to output thread stack.
All busy thread are stop in msgpack calling.
What's happend? I need help, thank all of us.

This is a thread stack, and serveral threads all stop here:getDeclaredConstructors0
```
"IThread-16-10.0.1.109:8001" #45 prio=5 os_prio=0 tid=0x00007f57a07b7000 nid=0x4ec runnable [0x00007f5769fdf000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.getConstructor(Class.java:1825)
        at org.msgpack.template.builder.DefaultBuildContext.buildInstance(DefaultBuildContext.java:78)
        at org.msgpack.template.builder.BuildContext.build(BuildContext.java:68)
        at org.msgpack.template.builder.DefaultBuildContext.buildTemplate(DefaultBuildContext.java:56)
        at org.msgpack.template.builder.JavassistTemplateBuilder.buildTemplate(JavassistTemplateBuilder.java:118)
        at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(AbstractTemplateBuilder.java:61)
        at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:562)
        - locked <0x00000000b3745070> (a org.msgpack.template.TemplateRegistry)
        at org.msgpack.template.TemplateRegistry.lookupAfterBuilding(TemplateRegistry.java:472)
        at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:251)
        - locked <0x00000000b3745070> (a org.msgpack.template.TemplateRegistry)
        at org.msgpack.template.TemplateRegistry.lookupGenericTypeImpl0(TemplateRegistry.java:320)
        at org.msgpack.template.TemplateRegistry.lookupGenericTypeImpl(TemplateRegistry.java:308)
        at org.msgpack.template.TemplateRegistry.lookupGenericType(TemplateRegistry.java:280)
        at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:205)
        - locked <0x00000000b3745070> (a org.msgpack.template.TemplateRegistry)
        at org.msgpack.template.builder.JavassistTemplateBuilder.toTemplate(JavassistTemplateBuilder.java:128)
        at org.msgpack.template.builder.JavassistTemplateBuilder.buildTemplate(JavassistTemplateBuilder.java:116)
        at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(AbstractTemplateBuilder.java:61)
        at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:562)
        - locked <0x00000000b3745070> (a org.msgpack.template.TemplateRegistry)
        at org.msgpack.template.TemplateRegistry.lookupAfterBuilding(TemplateRegistry.java:472)
        at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:251)
        - locked <0x00000000b3745070> (a org.msgpack.template.TemplateRegistry)
        at org.msgpack.MessagePack.write(MessagePack.java:195)
        at net.szrobot.ibase.DataPublisher.sendRTMsgEvent(DataPublisher.java:154)
```

I use @Message annotation to pack mssage.
and java object contants a Integer and another @Message annotated object.

**Comment by xerial** [comment]
@yinhaibo Unfortunately we now longer support msgpack v6. Consider using msgpack 0.8.x

**Comment by yinhaibo** [comment]
I found this issue only occurred in using annotation method.

**Comment by uprazapati** [comment]
> I found this issue only occurred in using annotation method.

@yinhaibo Did you see the same issue in v08 ? If not, can you suggest me how did you get out of this issue ?

**Comment by uprazapati** [comment]
> @yinhaibo Unfortunately we no longer support msgpack v6. Consider using msgpack 0.8.x

@xerial Even if you don't support v06 now but can you confirm that v06 have high memory usage issues which are taken care in v08. I am asking this because I see that in v06 write method in MessagePack.java it creates a Packer object on heap every time a write call is made.

**Comment by uprazapati** [comment]
@xerial  
Even if you don't support v06 now but can you confirm that v06 have high memory usage issues which are taken care in v08. I am asking this because I see that in v06 write method in MessagePack.java it creates a Packer object on heap every time a write call is made.
