### ISSUE TITLE
 java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: XXX

### ISSUE THREAD

**Issue by zeroxychn** [msgpack/msgpack-java#447]
I have a problem for msgpack. When my program running, sometime it throw the exception:

```
org.msgpack.MessageTypeException: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  com.egc.MsgTest _$$_t;
  if ($2 == null) {
    _$$_t = new com.egc.MsgTest();
  } else {
    _$$_t = (com.egc.MsgTest) $2;
  }
  $1.readArrayBegin();
  if ($1.trySkipNil()) {  } else {
    org.msgpack.template.builder.DefaultBuildContext.readPrivateField($1, _$$_t, com.egc.MsgTest.class, "intValue", templates[0]);
  }
  $1.readArrayEnd();
  return _$$_t;
}

	at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:575)
	at org.msgpack.template.TemplateRegistry.lookupAfterBuilding(TemplateRegistry.java:472)
	at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:251)
	at org.msgpack.MessagePack.read(MessagePack.java:370)
	at com.egc.App.main(App.java:30)
Caused by: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  com.egc.MsgTest _$$_t;
  if ($2 == null) {
    _$$_t = new com.egc.MsgTest();
  } else {
    _$$_t = (com.egc.MsgTest) $2;
  }
  $1.readArrayBegin();
  if ($1.trySkipNil()) {  } else {
    org.msgpack.template.builder.DefaultBuildContext.readPrivateField($1, _$$_t, com.egc.MsgTest.class, "intValue", templates[0]);
  }
  $1.readArrayEnd();
  return _$$_t;
}

	at org.msgpack.template.builder.BuildContext.build(BuildContext.java:73)
	at org.msgpack.template.builder.DefaultBuildContext.buildTemplate(DefaultBuildContext.java:56)
	at org.msgpack.template.builder.JavassistTemplateBuilder.buildTemplate(JavassistTemplateBuilder.java:118)
	at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(AbstractTemplateBuilder.java:61)
	at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:562)
	... 4 more
Caused by: javassist.CannotCompileException: by java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "com/egc/MsgTest_$$_Template_1067780644_0"
	at javassist.ClassPool.toClass(ClassPool.java:1099)
	at javassist.CtClass.toClass(CtClass.java:1265)
	at org.msgpack.template.builder.BuildContext.createClass(BuildContext.java:154)
	at org.msgpack.template.builder.BuildContext.build(BuildContext.java:68)
	... 8 more
Caused by: java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "com/egc/MsgTest_$$_Template_1067780644_0"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.ClassPool.toClass2(ClassPool.java:1112)
	at javassist.ClassPool.toClass(ClassPool.java:1093)
	... 11 more
```
So i write some codes for test. I found if run serialization method  circularly, it will throw exception  regularly.  There is my test code:
The Pojo Class:
```
public class MsgTest {

    @Index(0)
    private Integer intValue;

    public Integer getIntValue() {
        return intValue;
    }

    public void setIntValue(Integer intValue) {
        this.intValue = intValue;
    }

    public MsgTest() {
    }

}
```
And The Main Method:
```
public class App 
{
    public static void main( String[] args ) {
        Integer aBeginValue = 0x5a000000;
        Integer aEndValue = 0x5b000000;
        Integer aInt = aBeginValue;
        try{
            while(true){
                byte[] cc = new byte[6];
                cc[0] = (byte) 0x91;
                cc[1] = (byte) 0xce;
                cc[2] = (byte) (aInt >> 24);
                cc[3] = (byte) (aInt >> 16);
                cc[4] = (byte) (aInt >> 8);
                cc[5] = (byte) (aInt >> 0);
                MessagePack mp = new MessagePack();
                MsgTest aValue = mp.read(cc, MsgTest.class);
                aInt++;
                if (aInt == aEndValue){
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            org.slf4j.LoggerFactory.getLogger(App.class).debug("{}", aInt - aBeginValue);
        }
}
```

I use the version 0.6.12(0.6.11). I want to use the new version 0,8.x also , but there are so many running-codes to change. so @komamitsu expect you to fix the bug, thank u!

**Comment by zeroxychn** [comment]
please close this issue. i decide to upgrade my code to v0.8, thanks for read. @xerial

**Comment by xerial** [comment]
@zeroxychn Good. Thanks for upgrading to the latest version.
