### ISSUE TITLE
register an external Class by URLClassLoader throws an Exception

### ISSUE THREAD

**Issue by Alanscut** [msgpack/msgpack-java#518]
**My intention is to serialize and deserialize an object which is delivered by external jar.**
```java
URL url = new URL("file:///temp/class/VO.jar");
URLClassLoader classLoader = new URLClassLoader(new URL[]{url});
clazz = classLoader.loadClass("VO");
classLoader.close();

MessagePack msgPack = new MessagePack();
msgPack.register(this.testClass); // failed
```
* when I register above clazz to MsgPack, it will report an error:
```
builder: 
{
  if ($2 == null) {
    if ($3) {
      throw new org.msgpack.MessageTypeException("Attempted to write null");
    }
    $1.writeNil();
    return;
...
	at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:575)
	at org.msgpack.template.TemplateRegistry.register(TemplateRegistry.java:158)
	at org.msgpack.MessagePack.register(MessagePack.java:602)
	at performance.serialize.impl.MsgpackInstance.<init>(MsgpackInstance.java:24)
	at performance.Main2.benchAll(Main2.java:101)
	at performance.Main2.main(Main2.java:49)
Caused by: org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
...
```
* dependency:
```
<dependency>
    <groupId>org.msgpack</groupId>
    <artifactId>msgpack</artifactId>
    <version>0.6.12</version>
</dependency>
```
* this is my VO:
```
public class Person {

    private static final long serialVersionUID = 1L;

    private String name;;
    private int age;

    public Person(){
    }

    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setAge(int age) {
        this.age = age;
    }
	
}
```

**Comment by Alanscut** [comment]
setClassLoader before regitering the class is the right way.
