### ISSUE TITLE
JSON problem

### ISSUE THREAD

**Issue by verandar** [msgpack/msgpack-java#61]
```java
import java.io.IOException;

import org.msgpack.MessagePack;
import org.msgpack.packer.BufferPacker;
import org.msgpack.unpacker.Unpacker;
import org.msgpack.util.json.JSON;

public class JSONTest {

    public static void main(String[] args) throws IOException {
        System.out.println("new MessagePack()");
        test(new MessagePack());
        
        System.out.println("new JSON()");
        test(new JSON());
    }

    private static void test(MessagePack msgpack) throws IOException {
        BufferPacker packer = msgpack.createBufferPacker();
        packer.write(1);
        packer.write(2);
        byte[] bytes = packer.toByteArray();

        Unpacker unpacker = msgpack.createBufferUnpacker(bytes);
        System.out.println(unpacker.readInt());
        System.out.println(unpacker.readInt());
    }
}
```

Result
================================
new MessagePack()
1
2
new JSON()
12

Exception
================================
Exception in thread "main" java.io.IOException: Unexpected token END OF FILE at position 0.
	at org.msgpack.util.json.JSONUnpacker.nextValue(JSONUnpacker.java:58)
	at org.msgpack.unpacker.Converter.ensureValue(Converter.java:54)
	at org.msgpack.unpacker.Converter.getTop(Converter.java:274)
	at org.msgpack.unpacker.Converter.readInt(Converter.java:130)
	at JSONTest.test(JSONTest.java:26)
	at JSONTest.main(JSONTest.java:15)
Caused by: Unexpected token END OF FILE at position 0.
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
	at org.msgpack.util.json.JSONUnpacker.nextValue(JSONUnpacker.java:55)
	... 5 more

Version
================================
0.6.8

**Comment by komamitsu** [comment]
@verandar Really sorry for late reply. org.msgpack.util.json.JSONPacker still has some problems but we're concentrating on msgpack-v07. So we don't recommend JSONPacker in v0.6.x.

In v0.7.x, we added https://github.com/msgpack/msgpack-java/tree/v07-develop/msgpack-jackson. With the library, you can convert Java objects from/to MessagePack or JSON format in the same way.

**Comment by komamitsu** [comment]
I'm closing this issue. Please re-open it if you still have any problem.
