### ISSUE TITLE
Failure caused by nanosecond precision with Java 17 on Linux

### ISSUE THREAD

**Issue by sndmn1** [msgpack/msgpack-java#743]
https://github.com/msgpack/msgpack-java/blob/4b3895488c1263bf91489748bdceac0069bca85e/msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackGenerator.java#L253

When using org.springframework.data.annotation.LastModifiedDate on a Linux machine, a default precision of nanoseconds is used by Java 17. This causes the following error when serializing the data using MessagePack:
```
java.lang.IllegalArgumentException: MessagePack cannot serialize a BigDecimal that can't be represented as double. 1688078504.174525930
	at org.msgpack.jackson.dataformat.MessagePackGenerator.packBigDecimal(MessagePackGenerator.java:275)
	at org.msgpack.jackson.dataformat.MessagePackGenerator.pack(MessagePackGenerator.java:233)
	at org.msgpack.jackson.dataformat.MessagePackGenerator.packArray(MessagePackGenerator.java:306)
	at org.msgpack.jackson.dataformat.MessagePackGenerator.pack(MessagePackGenerator.java:224)
	at org.msgpack.jackson.dataformat.MessagePackGenerator.packObject(MessagePackGenerator.java:292)
	at org.msgpack.jackson.dataformat.MessagePackGenerator.flush(MessagePackGenerator.java:521)
	at org.msgpack.jackson.dataformat.MessagePackGenerator.close(MessagePackGenerator.java:505)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4573)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3844)
```

This did not cause any issues on Java 11 as the default precision appears to be in microseconds.

**Comment by komamitsu** [comment]
MessagePack format can't represent the precision. Please follow this https://github.com/msgpack/msgpack-java/blob/develop/msgpack-jackson/README.md#serialize-and-deserialize-bigdecimal-as-str-type-internally-in-messagepack-format

**Comment by sndmn1** [comment]
@komamitsu, thanks for the suggestion. This has resolved our issue.
